on:
  push:
    branches:
      - "master"

jobs:
  build-package:
    strategy:
      matrix:
        variant: ["v5", "v5d"]

    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Build dependencies"
        run: "sudo ./install_dependencies.sh"

      - name: "Prepare build script"
        run: "./prepare_script.sh ${{ matrix.variant }}"

      - name: "Build toolchain"
        working-directory: "nds-gnu-toolchain"
        run: "./build_elf_toolchain.sh"

      - name: "Create toolchain archive"
        working-directory: "nds-gnu-toolchain"
        run: "tar -cJf toolchain-${{ matrix.variant }}.tar.xz nds32le-elf-newlib-${{ matrix.variant }}"

      - name: "Upload toolchain artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: toolchain-${{ matrix.variant }}
          path: nds-gnu-toolchain/toolchain-${{ matrix.variant }}.tar.xz

  build-container:
    strategy:
      matrix:
        variant: ["v5", "v5d"]
  
    runs-on: "ubuntu-latest"
    needs: "build-package"
    steps:
      - name: "Setup Docker Buildx"
        uses: "docker/setup-buildx-action@v2"
      
      - name: "Login to GitHub package registry"
        uses: "docker/login-action@v2"
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Download toolchain artifact"
        uses: actions/download-artifact@v3
          with:
          name: toolchain-${{ matrix.variant }}
          path: "container"

      - name: "Build and push image"
        uses: "docker/build-push-action@v4"
        with:
          context: container
          push: true
          tags: "ghcr.io/${{ github.repository_owner }}/embedded-builder-andesv5:${{ matrix.variant }}"
