on:
  push:
    branches:
      - "master"

jobs:
  build:
    strategy:
      matrix:
        variant: ["v5", "v5d"]

    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Build dependencies"
        run: "sudo ./install_dependencies.sh"

      - name: "Prepare build script"
        run: "./prepare_script.sh ${{ matrix.variant }}"

      - name: "Build toolchain"
        working-directory: "nds-gnu-toolchain"
        run: "./build_elf_toolchain.sh"

      - name: "Send toolchain to docker build directory"
        working-directory: "nds-gnu-toolchain"
        run: "tar -cvf ../container/toolchain.tar nds32le-elf-newlib-${{ matrix.variant }}"

      - name: "Setup Docker Buildx"
        uses: "docker/setup-buildx-action@v2"
      
      - name: "Login to GitHub package registry"
        uses: "docker/login-action@v2"
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Build and push image"
        uses: "docker/build-push-action@v4"
        with:
          context: container
          push: true
          tags: "ghcr.io/${{ github.actor }}/embedded-builder-andesv5:${{ matrix.variant }}"